### ISSUE TITLE
nativefiledialog as submodule

### ISSUE THREAD

**Issue by DenisKolodin** [saurvs/nfd-rs#2]
PR https://github.com/mlabbe/nativefiledialog/pull/19 was merged. It makes possible to use it as submodule.

@saurvs @emoon Let's consider to use it mentioned way.

Now *nativefiledialog* (devel branch) uses *premake 5* and have `Makefiles` to popular OS. I offer:

- [x] Use **nativefiledialog** as git submodule
- [x] Remove `nfd` folder with local version (and stop to maintain it)
- [x] Update and still use `build.rs` script

Any ideas? Caveats?

**Comment by emoon** [comment]
That sounds fine. I very much prefer that we use build.rs as it allows Rust users to use the library without needing external build tools.

**Comment by DenisKolodin** [comment]
I've made a PR #3 to fix it.

**Comment by DenisKolodin** [comment]
It was merged.
