### ISSUE TITLE
Cant navigate in filesystem

### ISSUE THREAD

**Issue by ctaque** [saurvs/nfd-rs#23]
When I open the system dialog with open_file_dialog I can't navigate between the folders :

```rust
let result = nfd::open_file_dialog(Some("png"), Some("~/Pictures")).unwrap_or_else(|e| {
       panic!(e);
});
```

The buttons event on the sidebar are disabled, and I don't land on the Pictures folder

**Comment by mlabbe** [comment]
This should be fixed in the upstream project devel branch by https://github.com/mlabbe/nativefiledialog/commit/eb29acc563cbb26390653bf3dc57a08d8f09074d as of today.
